#!/usr/bin/env python

import sys
import os
import pathlib
from enum import Enum
from collections import namedtuple


def _print_usage(program_name):
    usage = (
        f"\n{program_name} usage instructions:\n\n"
        f"  {program_name} (--help | -h)\n"
        f"     print help text and exit\n\n"
        f"  {program_name} (--verbose) in.asm\n"
        f"     assemble in.asm to in.hack\n\n"
        f"  {program_name} (--verbose) my/path/in.asm\n"
        f"     assemble my/path/in.asm to my/path/in.hack\n\n"
        "✌️")
    print(usage)

Command = namedtuple('Command',
                     ['type',
                      'operation',
                      'args',
                      'text',
                      'source_line_number'])

C = Enum('CommandType',
         ['ARITHMETIC',
          'PUSH',
          'POP',
          'LABEL',
          'GOTO',
          'IF',
          'FUNCTION',
          'RETURN',
          'CALL'])

class VMParser(object):

    _command_map = {'add' : (C.ARITHMETIC, 0),
                    'sub' : (C.ARITHMETIC, 0),
                    'and' : (C.ARITHMETIC, 0),
                    'or'  : (C.ARITHMETIC, 0),
                    'eq'  : (C.ARITHMETIC, 0),
                    'gt'  : (C.ARITHMETIC, 0),
                    'lt'  : (C.ARITHMETIC, 0),
                    'not' : (C.ARITHMETIC, 0),
                    'neg' : (C.ARITHMETIC, 0),
                    'push': (C.PUSH, 2),
                    'pop' : (C.POP,  2)
                    }

    def __init__(self, inf):
        self.inf = inf
        self.line_number = 0

    def __call__(self):
        for line in self.inf:
            self.line_number += 1
            line = self._clean_line(line)
            if len(line) == 0 or line.startswith('//'):
                continue
            else:
                command = self._parse_command(line.split())
                yield command

    def _parse_command(self, fields):
        try:
            command_type, expected_n_args = self._command_map[fields[0]]
        except KeyError:
            self._raise_error(f"Unknown command type: {fields[0]}")

        if len(fields[1:]) != expected_n_args:
               self._raise_error(
                   f"Expected {expected_n_args} arguments for command "
                   f"{fields[0]}, but received "
                   f"{len(fields[1:])}: {' '.join(fields)}")

        return Command(type=command_type,
                       operation=fields[0],
                       args=fields[1:],
                       text=' '.join([fields[0]] + fields[1:]),
                       source_line_number=self.line_number)

    def _clean_line(self, line):
        return line.strip().split('//')[0]

    def _raise_error(self,
                     message):
        raise ValueError(f'Line {self.line_number}: {message}')


class AsmWriter(object):

    _segment_map = {'local': 'LCL',
                    'argument': 'ARG',
                    'this': 'THIS',
                    'that': 'THAT',
                    # confirm that temp should be defined here, not in
                    # the assembler
                    'temp': 5
                    }

    _pointer_map = {'0': 'THIS',
                    '1': 'THAT'}

    def __init__(self, outf):
        self.outf = outf
        self.command_number = 0
        self._label_counter = 0

    def __call__(self, command):
        self._command = command
        self._write_comment(f"Start {command.type}")
        self._write_comment(command.text)

        if command.type == C.PUSH:
            self._push(command)
        elif command.type == C.POP:
            self._pop(command)
        elif command.type == C.ARITHMETIC:
            self._arithmetic(command)
        else:
            raise NotImplementedError(
                f"Unknown command type: {command.type}")

        self._write_comment(f"End {command.type}", double_newline=True)

    def _raise_error(self,
                     message):
        # referencing the line number feels like bad encapsulation,
        # i should move validation that uses this to the parser
        raise ValueError(
            f"Line {self._command.source_line_number}: {message}")

    def _write_comment(self, comment, double_newline=False):
        self.outf.write(f"// {comment}\n")
        if double_newline:
            self.outf.write(f"\n")

    def _write_command(self, command):
        self.outf.write(f"{command}\n")

    def _increment_stack_pointer(self):
        self._write_comment("SP++")
        self._write_command("@SP")
        self._write_command("M = M + 1")

    def _decrement_stack_pointer(self):
        self._write_comment("SP--")
        self._write_command("@SP")
        self._write_command("M = M - 1")

    def _next_label(self):
        result = f"LABEL.{self._label_counter}"
        self._label_counter += 1
        return result

    def _push(self, command):
        segment, index = command.args
        if segment == 'constant':
            self._write_command(f"@{index}")
            self._write_command("D = A")
        elif segment == 'temp':
            segment_ref = self._segment_map[segment]
            address = segment_ref + int(index)
            if address < 5 or address > 12:
                self._raise_error(
                    f"Address {address} out of temp range 5-12.")
            self._write_command(f"@{address}")
            self._write_command("D = M")
        elif segment == 'pointer':
            try:
                pointer_ref = self._pointer_map[index]
            except KeyError:
                self._raise_error(
                    "Index for pointer segment must be either 0 or 1, "
                    f"but received {index}.")
            self._write_command(f"@{pointer_ref}")
            self._write_command("D = M")
        else:
            try:
                segment_ref = self._segment_map[segment]
            except KeyError:
                self._raise_error(f"Unknown push command segment: {segment}")
            self._write_command(f"@{segment_ref}")
            self._write_command("D = M")
            self._write_command(f"@{index}")
            self._write_command(f"A = D + A")
            self._write_command("D = M")

        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command("M = D")
        self._increment_stack_pointer()

    def _pop(self, command):
        segment, index = command.args

        if segment == 'temp':
            segment_ref = self._segment_map[segment]
            address = segment_ref + int(index)
            if address < 5 or address > 12:
                self._raise_error(
                    f"Address {address} out of temp range 5-12.")
            self._write_command(f"@{address}")
            self._write_command("D = A")
        elif segment == 'pointer':
            try:
                pointer_ref = self._pointer_map[index]
            except KeyError:
                self._raise_error(
                    "Index for pointer segment must be either 0 or 1, "
                    f"but received {index}.")
            self._write_command(f"@{pointer_ref}")
            self._write_command("D = A")
        else:

            try:
                segment_ref = self._segment_map[segment]
            except KeyError:
                self._raise_error(f"Unknown pop command segment: {segment}")
            self._write_command(f"@{segment_ref}")
            self._write_command("D = M")
            self._write_command(f"@{index}")
            self._write_command(f"D = D + A")
        # this reference to the R13 virtual register add two additional
        # memory references on every pop. is that necessary?
        # it's storing the destination address
        self._write_command("@R13")
        self._write_command("M = D")

        self._decrement_stack_pointer()
        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command("D = M")

        self._write_command("@R13")
        self._write_command("A = M")
        self._write_command("M = D")

    def _apply_one_operand_operation(self, op):
        self._decrement_stack_pointer()
        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command(f"M = {op}M")
        self._increment_stack_pointer()

    def _load_operand_to_D(self):
        self._decrement_stack_pointer()
        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command("D = M")

    def _apply_two_operand_operation(self, op):
        self._load_operand_to_D()
        self._decrement_stack_pointer()
        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command(f"M = M {op} D")
        self._increment_stack_pointer()

    def _apply_comparison_operation(self,
                                    jump_true,
                                    jump_false):
        self._load_operand_to_D()

        self._decrement_stack_pointer()

        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command("D = M - D")

        label_true = self._next_label()
        label_false = self._next_label()
        label_jmp = self._next_label()

        self._write_command(f"@{label_true}")
        self._write_command(f"D;{jump_true}")

        self._write_command(f"@{label_false}")
        self._write_command(f"D;{jump_false}")

        self._write_command(f"({label_true})")
        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command("M = -1")
        self._write_command(f"@{label_jmp}")
        self._write_command("0;JMP")

        self._write_command(f"({label_false})")
        self._write_command("@SP")
        self._write_command("A = M")
        self._write_command("M = 0")
        self._write_command(f"@{label_jmp}")
        self._write_command("0;JMP")

        self._write_command(f"({label_jmp})")
        self._increment_stack_pointer()

    def _arithmetic(self, command):
        if command.operation == 'add':
            self._apply_two_operand_operation('+')
        elif command.operation == 'sub':
            self._apply_two_operand_operation('-')
        elif command.operation == 'or':
            self._apply_two_operand_operation('|')
        elif command.operation == 'and':
            self._apply_two_operand_operation('&')
        elif command.operation == 'neg':
            self._apply_one_operand_operation('-')
        elif command.operation == 'not':
            self._apply_one_operand_operation('!')
        elif command.operation == 'eq':
            self._apply_comparison_operation(
                jump_true='JEQ', jump_false='JNE')
        elif command.operation == 'lt':
            self._apply_comparison_operation(
                jump_true='JLT', jump_false='JGE')
        elif command.operation == 'gt':
            self._apply_comparison_operation(
                jump_true='JGT', jump_false='JLE')
        else:
            raise NotImplementedError(
                f"Unknown arithmetic command: {command.operation}")

    def finalize_program(self):
        self._write_comment("Terminal infinite loop")

        label = self._next_label()

        self._write_command(f"({label})")
        self._write_command(f"@{label}")
        self._write_command("0;JMP")


def vm_translator(input_fp,
                  output_fp,
                  verbose=False):
    """
    """
    with open(input_fp) as inf, \
         open(output_fp, 'w') as outf:

        vm_parser = VMParser(inf)
        asm_writer = AsmWriter(outf)

        for command in vm_parser():
            if verbose:
                print(
                 f"{command.type}: "
                 f"{command.operation} {' '.join(command.arguments)}")
            asm_writer(command)

        asm_writer.finalize_program()


if __name__ == "__main__":
    if len(sys.argv) == 1 or '--help' in sys.argv or '-h' in sys.argv:
        _print_usage(program_name=pathlib.Path(sys.argv[0]).name)
        exit(0)

    verbose = '--verbose' in sys.argv

    input_fp = pathlib.Path(sys.argv[-1])

    if not input_fp.exists():
        raise ValueError(f"Input path doesn't exist: {input_fp}")

    if not input_fp.suffix == '.vm':
        raise ValueError(
            "Input path must have extension .vm, "
            f"but found {input_fp.suffix}")

    output_fp = input_fp.with_suffix('.asm')

    if verbose:
        print(f"Input path: {input_fp}")
        print(f"Output path: {output_fp}")

    vm_translator(input_fp, output_fp, verbose=verbose)